name: deploy my id card server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ddserp/public_html/testt.dds-erp.com/school-erp-backend

            git config --global --add safe.directory /home/ddserp/public_html/testt.dds-erp.com/school-erp-backend

            git pull origin main

            cd admissionService

            npm install

            node app.js