name: Deploy School ERP Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/apps/school-erp-backend

            git config --global --add safe.directory /var/www/apps/school-erp-backend

            git pull origin main

            cd admissionService

            npm install

            npx sequelize db:migrate

            pm2 restart admission-api